package dadkvs.server;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsConsole;
import dadkvs.DadkvsConsoleServiceGrpc;
import io.grpc.stub.StreamObserver;

public class DadkvsConsoleServiceImpl extends DadkvsConsoleServiceGrpc.DadkvsConsoleServiceImplBase {

	DadkvsServerState server_state;
	public DadkvsConsoleServiceImpl(DadkvsServerState state) {
		this.server_state = state;
	}

	@Override
	public void setleader(DadkvsConsole.SetLeaderRequest request,
			StreamObserver<DadkvsConsole.SetLeaderReply> responseObserver) {
		// for debug purposes
		System.out.println(request);

		boolean response_value = true;
		this.server_state.i_am_leader = request.getIsleader();

		// for debug purposes
		System.out.println("I am the leader = " + this.server_state.i_am_leader);

		this.server_state.main_loop.wakeup();

		DadkvsConsole.SetLeaderReply response = DadkvsConsole.SetLeaderReply.newBuilder()
				.setIsleaderack(response_value).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}

	@Override
    public void setdebug(DadkvsConsole.SetDebugRequest request, StreamObserver<DadkvsConsole.SetDebugReply> responseObserver) {
        System.out.println(request);
        int mode = request.getMode();
        boolean response_value = true;

        switch (mode) {
            case 1:
                // debugmode1: Crash the server
                System.out.println("Debug Mode 1: Crashing the server.");
                System.exit(1);
                break;

            case 2:
                // debugmode2: Freeze the server (block all client requests)
                System.out.println("Debug Mode 2: Freezing the server.");
				server_state.setFreezeLock(true);
                break;

            case 3:
                // debugmode3: Un-freeze the server (resume handling client requests)
                System.out.println("Debug Mode 3: Un-freezing the server.");
				server_state.setFreezeLock(false);
                break;

            case 4:
                // debugmode4: Slow-mode on (apply random delays)
                System.out.println("Debug Mode 4: Turning slow mode ON.");
                server_state.setSlowMode(true);
                break;

            case 5:
                // debugmode5: Slow-mode off (remove random delays)
                System.out.println("Debug Mode 5: Turning slow mode OFF.");
                server_state.setSlowMode(false);
                break;

            default:
                System.out.println("Unknown debug mode: " + mode);
                response_value = false;
        }

        this.server_state.debug_mode = mode;
        this.server_state.main_loop.wakeup();

        DadkvsConsole.SetDebugReply response = DadkvsConsole.SetDebugReply.newBuilder()
                .setAck(response_value).build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

}
